---

#-- some 'global rule variables'
_rule:
  name: "fah"
  version: v7.6.21-deb-volume
  build: "0.4.4"
  #build_path: "{{playbook_dir}}/build"
  build_path: "/tmp/"
  rootLocation: "/data/projects/FAH-devel"


#-- Configuration parameters  to run, build and/or archive F@H container / image
fah:
  name: "{{_rule.name}}"
  fullname: "{{_rule.name}}"
  tag: "{{_rule.build}}"
  config: #-- settings for the config.xml file of FAHClient
    path: "{{_rule.build_path}}/{{_rule.name}}/config.xml"
    team: "246361" #-- your Folding@Home team number, use "0" if you're not part a a team (yet)
    user: "brtlvrs" #-- your username for Folding@Home
    passkey: "7ce465c5bcaf2e327ce465c5bcaf2e32"  #-- your passkey for Folding@Home
    fold_anon: "false" 
    gpu: "false"
    power: medium #-- Options: light, medium or full
    allow: "0.0.0.0/0"
    web_allow: "0.0.0.0/0"
    command_allow_no_pass: "0.0.0.0/0"
    smp: "true"
  dockerhub:
    path: "{{_rule.rootLocation}}/dockerhub"
  docker: #-- settings for the docker commands
    image: #-- docker build settings
      dockerfile: "{{_rule.build_path}}"
      build:
        path: "{{_rule.build_path}}/{{_rule.name}}" #--path to place dockerfile and build image from
      archive:
        path: "{{_rule.rootLocation}}/archive/{{_rule.name}}" #-- path to archive image
    container: #-- docker run settings
      ipv4: "{{ansible_eth0.ipv4.address}}" #-- this is the ipv4 address of the host where docker is running
      control_port: "36330" #"36330" #-- default for Folding@Home client FAHClient is 36330
      web_port: "7396" #"7396"  #-- default for Folding@Home client FAHClient 7396
      cpu:
        shares: "768" #-- default is 1024
      mem:
        memory: "765M"  #- max amount of memory to use (rest is swap)
        memory_swap: "2G" #-- total ammount of memory

help:
    tags_explenation:
      rm_container : remove docker container
      rm_image     : remove docker container and image
      build        : (re)build image, remove container, remove image then (re)build image
      run          : (re)build container, remove container, run container (data volume is not removed)
      clean_run    : remove container with its volume and run container
      run_only     : don't rebuild image, only (re)run container
      stop         : stop running container
      archive      : archive image to .tar, first (re)build image, will not work if container is present
      archive_only : archive image to .tar
