---
#
#  tags
#

#  stop             stop running the container
#  run_clean        Rebuild docker image, remove container with volume and run container
#  rm_container     Remove container.
#  rm_image         Removes image and container.
#  build            build the image. (whill be used when no tag is given)
#  run              [default], (re)build the image run the container, using exisiting volume, if present
#  archive          (re)build the image and archive it to an .tar file
#  archive_only     only run archive tasks
#  build_only       only run build tasks. Container will be stopped and removed.
#  run_only         Only run container.
#

#-- 
- name: display custom variables
  #-- debug task to display custom created variables
  tags:
  - always
  debug:
    var: "{{ item }}"
    verbosity: 1
  loop:
  - build_folder
  - fah

- name: "find Folding@Home container: {{fah.name}}"
  #-- Check if Folding@Home container exists
  tags:
    - run
    - rm_all
    - rm_container
    - rm_image
    - stop
    - clean_run
  docker_container_info:
    name: "{{fah.name}}"
  register: fah_container

- name: "stop Folding@Home container: {{fah.name}}"
  tags:
    - rm_container
    - rm_all
    - rm_image
    - rm_all
    - stop
    - clean_run
  docker_container:
    name: "{{fah.name}}"
    state: stopped
  when: fah_container.exists

- name: "remove Folding@Home container: {{fah.name}}"
  tags:
    - rm_container
    - rm_image
    - build
    - run
  when: fah_container.exists
  docker_container:
    name: "{{fah.name}}"
    state: absent

- name: "remove Folding@Home container incl. volume: {{fah.name}}"
  tags:
    - never #only run task when tags are explicity given 
    - rm_all
    - clean_run
  when: fah_container.exists
  docker_container:
    name: "{{fah.name}}"
    state: absent
    keep_volumes: "no"

- name: "remove Folding@Home docker image: {{fah.name}}:{{fah.tag}}" 
  tags:
    - rm_image
    - build_only
    - run
    - buid
    - archive
    - rm_all
  docker_image:
    name: "{{fah.name}}" 
    tag: "{{fah.tag}}" 
    state: absent


- name: check build folder
  tags:
    - never
    - build_only
    - build
    - run 
    - archive
  file:
    path: "{{build_folder}}"
    state: directory
    mode: '0755'


- name: bugfix 'invalid selinux context' - create config.xml
  tags:
    - build
    - build_only
    - run
    - archivve
  file:
    path:  "{{build_folder}}/config.xml"
    state: touch

- name: templating build content
  tags:
    - Archive
    - build_only
    - build
    - run
  template:
    src: "{{item}}.j2"
    dest: "{{build_folder}}/{{item}}"
  loop:
    - config.xml
    - dockerfile


- name: "build Folding@Home docker image: {{fah.name}}:{{fah.tag}}" 
  tags:
    - build
    - build_only
    - run
    - Archive
  docker_image:
    build:
      pull: "false"
      path: "{{build_folder}}"
    source: build
    name: "{{fah.name}}" 
    tag: "{{fah.tag}}" 
    push: false

- name: "run Folding@home container: {{fah.name}} from image: {{fah.name}}:{{fah.tag}}" 
  tags:
    - run
    - run_only
    - clean_run
  docker_container:
    name: "{{fah.name}}"
    image: "{{fah.name}}:{{fah.tag}}"
    domainname: shire.loc
    state: started
    cleanup: yes
    cpu_shares: "{{fah.docker.container.cpu.shares}}"
#    networks: 
#      - name: bridge
    ports: 
      - "{{fah.docker.container.ipv4}}:{{fah.docker.container.web_port}}:7396/tcp"
      - "{{fah.docker.container.ipv4}}:{{fah.docker.container.control_port}}:36330/tcp"
    restart_policy: "unless-stopped"
    volumes:
      - "fahclient:/var/lib/fahclient"

- name: "create archiving location: {{fah.docker.image.archivepath}}"
  tags:
    - never
    - archive 
    - archive_only
  file:
    path: "{{fah.docker.image.archivepath}}"
    state: directory
    mode: '0755'

- name: "Archive / export dockerimage to: {{fah.docker.image.archivepath}}/{{fah.name}}-{{fah.tag}}.tar"
  tags:
    - never
    - archive 
    - archive_only
  docker_image:
    name: "{{fah.name}}"
    source: local  
    tag: "{{fah.tag}}"
    archive_path: "{{fah.docker.image.archivepath}}/{{fah.name}}-{{fah.tag}}.tar"

- name: Remove build folder and its content
  tags:
    - always
  file:
    path:  "{{playbook_dir}}/build"
    state: absent