#  Folding@Home : https://download.foldingathome.org
#
#  dockerfile based on https://github.com/yurinnick/folding-at-home-docker/blob/master/Dockerfile
#
# addendum :
#  - not using entrypoint.sh but used [ENTRYPOINT] and [CMD] instead
#  - using fahclient config.xml instead enviromental variables in entrypoint.sh
#  - config.xml is copied into image

FROM debian:stable-slim

RUN useradd --system folding && \
    mkdir -p /opt/fahclient/work && \
    # download and untar
    apt-get update -y && \
    apt-get install -y wget bzip2 && \
    wget https://download.foldingathome.org/releases/public/release/fahclient/debian-stable-64bit/v7.6/fahclient_7.6.13-64bit-release.tar.bz2 -O /tmp/fahclient.tar.bz2 && \
    tar -xjf /tmp/fahclient.tar.bz2 -C /opt/fahclient --strip-components=1 && \
    # fix permissions
    chown -R folding:folding /opt/fahclient && \
    # cleanup
    rm -rf /tmp/fahclient.tar.bz2 && \
    apt-get purge -y wget bzip2 && \
    apt-get clean autoclean && \
    apt-get autoremove --yes && \
    rm -rf /var/lib/apt/lists/*

#-- copy FAHCLient config.xml
COPY --chown=folding:folding config.xml /opt/fahclient/config.xml

USER folding
WORKDIR /opt/fahclient

#-- expose container ports 7396 (web) 36330 (control)
EXPOSE 7396 36330

ENTRYPOINT ["/opt/fahclient/FAHClient"]
CMD ["--config=/opt/fahclient/config.xml"]
